// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Chain string

const (
	ChainBnb Chain = "bnb"
	ChainSol Chain = "sol"
)

func (e *Chain) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Chain(s)
	case string:
		*e = Chain(s)
	default:
		return fmt.Errorf("unsupported scan type for Chain: %T", src)
	}
	return nil
}

type NullChain struct {
	Chain Chain `json:"chain"`
	Valid bool  `json:"valid"` // Valid is true if Chain is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChain) Scan(value interface{}) error {
	if value == nil {
		ns.Chain, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Chain.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChain) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Chain), nil
}

type DepositStatus string

const (
	DepositStatusPending  DepositStatus = "pending"
	DepositStatusCredited DepositStatus = "credited"
	DepositStatusSwept    DepositStatus = "swept"
	DepositStatusFailed   DepositStatus = "failed"
)

func (e *DepositStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DepositStatus(s)
	case string:
		*e = DepositStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DepositStatus: %T", src)
	}
	return nil
}

type NullDepositStatus struct {
	DepositStatus DepositStatus `json:"deposit_status"`
	Valid         bool          `json:"valid"` // Valid is true if DepositStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDepositStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DepositStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DepositStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDepositStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DepositStatus), nil
}

type KycTier string

const (
	KycTierNone     KycTier = "none"
	KycTierBasic    KycTier = "basic"
	KycTierEnhanced KycTier = "enhanced"
)

func (e *KycTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KycTier(s)
	case string:
		*e = KycTier(s)
	default:
		return fmt.Errorf("unsupported scan type for KycTier: %T", src)
	}
	return nil
}

type NullKycTier struct {
	KycTier KycTier `json:"kyc_tier"`
	Valid   bool    `json:"valid"` // Valid is true if KycTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKycTier) Scan(value interface{}) error {
	if value == nil {
		ns.KycTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KycTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKycTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KycTier), nil
}

type MultisigStatus string

const (
	MultisigStatusPending    MultisigStatus = "pending"
	MultisigStatusCollecting MultisigStatus = "collecting"
	MultisigStatusReady      MultisigStatus = "ready"
	MultisigStatusSubmitted  MultisigStatus = "submitted"
	MultisigStatusConfirmed  MultisigStatus = "confirmed"
	MultisigStatusExpired    MultisigStatus = "expired"
	MultisigStatusFailed     MultisigStatus = "failed"
)

func (e *MultisigStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MultisigStatus(s)
	case string:
		*e = MultisigStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MultisigStatus: %T", src)
	}
	return nil
}

type NullMultisigStatus struct {
	MultisigStatus MultisigStatus `json:"multisig_status"`
	Valid          bool           `json:"valid"` // Valid is true if MultisigStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMultisigStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MultisigStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MultisigStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMultisigStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MultisigStatus), nil
}

type Role string

const (
	RoleAdmin     Role = "admin"
	RoleTreasurer Role = "treasurer"
	RoleOperator  Role = "operator"
	RoleViewer    Role = "viewer"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type StaffStatus string

const (
	StaffStatusActive     StaffStatus = "active"
	StaffStatusSuspended  StaffStatus = "suspended"
	StaffStatusOffboarded StaffStatus = "offboarded"
)

func (e *StaffStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StaffStatus(s)
	case string:
		*e = StaffStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for StaffStatus: %T", src)
	}
	return nil
}

type NullStaffStatus struct {
	StaffStatus StaffStatus `json:"staff_status"`
	Valid       bool        `json:"valid"` // Valid is true if StaffStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStaffStatus) Scan(value interface{}) error {
	if value == nil {
		ns.StaffStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StaffStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStaffStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StaffStatus), nil
}

type SweepStatus string

const (
	SweepStatusPending   SweepStatus = "pending"
	SweepStatusSubmitted SweepStatus = "submitted"
	SweepStatusConfirmed SweepStatus = "confirmed"
	SweepStatusFailed    SweepStatus = "failed"
)

func (e *SweepStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SweepStatus(s)
	case string:
		*e = SweepStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SweepStatus: %T", src)
	}
	return nil
}

type NullSweepStatus struct {
	SweepStatus SweepStatus `json:"sweep_status"`
	Valid       bool        `json:"valid"` // Valid is true if SweepStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSweepStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SweepStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SweepStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSweepStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SweepStatus), nil
}

type Tier string

const (
	TierHot  Tier = "hot"
	TierCold Tier = "cold"
)

func (e *Tier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Tier(s)
	case string:
		*e = Tier(s)
	default:
		return fmt.Errorf("unsupported scan type for Tier: %T", src)
	}
	return nil
}

type NullTier struct {
	Tier  Tier `json:"tier"`
	Valid bool `json:"valid"` // Valid is true if Tier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTier) Scan(value interface{}) error {
	if value == nil {
		ns.Tier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Tier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Tier), nil
}

type Token string

const (
	TokenUSDT Token = "USDT"
	TokenUSDC Token = "USDC"
)

func (e *Token) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Token(s)
	case string:
		*e = Token(s)
	default:
		return fmt.Errorf("unsupported scan type for Token: %T", src)
	}
	return nil
}

type NullToken struct {
	Token Token `json:"token"`
	Valid bool  `json:"valid"` // Valid is true if Token is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullToken) Scan(value interface{}) error {
	if value == nil {
		ns.Token, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Token.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullToken) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Token), nil
}

type TxStatus string

const (
	TxStatusPending   TxStatus = "pending"
	TxStatusConfirmed TxStatus = "confirmed"
	TxStatusFailed    TxStatus = "failed"
	TxStatusDropped   TxStatus = "dropped"
)

func (e *TxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TxStatus(s)
	case string:
		*e = TxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TxStatus: %T", src)
	}
	return nil
}

type NullTxStatus struct {
	TxStatus TxStatus `json:"tx_status"`
	Valid    bool     `json:"valid"` // Valid is true if TxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TxStatus), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
	UserStatusClosed    UserStatus = "closed"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type WalletPurpose string

const (
	WalletPurposeDepositHd   WalletPurpose = "deposit_hd"
	WalletPurposeOperational WalletPurpose = "operational"
	WalletPurposeColdReserve WalletPurpose = "cold_reserve"
)

func (e *WalletPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WalletPurpose(s)
	case string:
		*e = WalletPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for WalletPurpose: %T", src)
	}
	return nil
}

type NullWalletPurpose struct {
	WalletPurpose WalletPurpose `json:"wallet_purpose"`
	Valid         bool          `json:"valid"` // Valid is true if WalletPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWalletPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.WalletPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WalletPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWalletPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WalletPurpose), nil
}

type WalletType string

const (
	WalletTypeMetamask            WalletType = "metamask"
	WalletTypePhantom             WalletType = "phantom"
	WalletTypeLedger              WalletType = "ledger"
	WalletTypeTrezor              WalletType = "trezor"
	WalletTypeHardwareViaMetamask WalletType = "hardware_via_metamask"
	WalletTypeOther               WalletType = "other"
)

func (e *WalletType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WalletType(s)
	case string:
		*e = WalletType(s)
	default:
		return fmt.Errorf("unsupported scan type for WalletType: %T", src)
	}
	return nil
}

type NullWalletType struct {
	WalletType WalletType `json:"wallet_type"`
	Valid      bool       `json:"valid"` // Valid is true if WalletType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWalletType) Scan(value interface{}) error {
	if value == nil {
		ns.WalletType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WalletType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWalletType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WalletType), nil
}

type WithdrawalStatus string

const (
	WithdrawalStatusPending    WithdrawalStatus = "pending"
	WithdrawalStatusApproved   WithdrawalStatus = "approved"
	WithdrawalStatusTimeLocked WithdrawalStatus = "time_locked"
	WithdrawalStatusExecuting  WithdrawalStatus = "executing"
	WithdrawalStatusCompleted  WithdrawalStatus = "completed"
	WithdrawalStatusCancelled  WithdrawalStatus = "cancelled"
	WithdrawalStatusFailed     WithdrawalStatus = "failed"
)

func (e *WithdrawalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WithdrawalStatus(s)
	case string:
		*e = WithdrawalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WithdrawalStatus: %T", src)
	}
	return nil
}

type NullWithdrawalStatus struct {
	WithdrawalStatus WithdrawalStatus `json:"withdrawal_status"`
	Valid            bool             `json:"valid"` // Valid is true if WithdrawalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWithdrawalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WithdrawalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WithdrawalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWithdrawalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WithdrawalStatus), nil
}

type AuditLog struct {
	ID           pgtype.UUID        `json:"id"`
	StaffID      pgtype.UUID        `json:"staff_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   *string            `json:"resource_id"`
	Changes      []byte             `json:"changes"`
	IpAddr       *string            `json:"ip_addr"`
	Ua           *string            `json:"ua"`
	PrevHash     *string            `json:"prev_hash"`
	Hash         string             `json:"hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Deposit struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Chain           Chain              `json:"chain"`
	Token           Token              `json:"token"`
	Amount          pgtype.Numeric     `json:"amount"`
	Status          DepositStatus      `json:"status"`
	ConfirmedBlocks int32              `json:"confirmed_blocks"`
	TxHash          *string            `json:"tx_hash"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DestinationWhitelist struct {
	ID        pgtype.UUID        `json:"id"`
	Chain     Chain              `json:"chain"`
	Address   string             `json:"address"`
	Label     *string            `json:"label"`
	AddedBy   pgtype.UUID        `json:"added_by"`
	AddedAt   pgtype.Timestamptz `json:"added_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type LedgerEntry struct {
	ID        pgtype.UUID        `json:"id"`
	TxID      pgtype.UUID        `json:"tx_id"`
	Account   string             `json:"account"`
	Debit     pgtype.Numeric     `json:"debit"`
	Credit    pgtype.Numeric     `json:"credit"`
	Currency  Token              `json:"currency"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MultisigApproval struct {
	ID                pgtype.UUID        `json:"id"`
	OpID              pgtype.UUID        `json:"op_id"`
	StaffID           pgtype.UUID        `json:"staff_id"`
	StaffSigningKeyID pgtype.UUID        `json:"staff_signing_key_id"`
	Signature         string             `json:"signature"`
	SignedAt          pgtype.Timestamptz `json:"signed_at"`
	// Slice 7 HW-attestation: raw bytes signed by the hardware wallet. NULL for hot-tier.
	AttestationBlob []byte `json:"attestation_blob"`
	// Slice 7 HW-attestation: device type ('ledger'|'trezor'|'none'). NULL for hot-tier.
	AttestationType *string `json:"attestation_type"`
}

type MultisigOperation struct {
	ID            pgtype.UUID        `json:"id"`
	WithdrawalID  pgtype.UUID        `json:"withdrawal_id"`
	Chain         Chain              `json:"chain"`
	OperationType string             `json:"operation_type"`
	MultisigAddr  string             `json:"multisig_addr"`
	RequiredSigs  int32              `json:"required_sigs"`
	CollectedSigs int32              `json:"collected_sigs"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	Status        MultisigStatus     `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type StaffMember struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	Name        string             `json:"name"`
	Role        Role               `json:"role"`
	Status      StaffStatus        `json:"status"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type StaffSigningKey struct {
	ID           pgtype.UUID        `json:"id"`
	StaffID      pgtype.UUID        `json:"staff_id"`
	Chain        Chain              `json:"chain"`
	Address      string             `json:"address"`
	Tier         Tier               `json:"tier"`
	WalletType   WalletType         `json:"wallet_type"`
	HwAttested   bool               `json:"hw_attested"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
}

type Sweep struct {
	ID         pgtype.UUID        `json:"id"`
	Chain      Chain              `json:"chain"`
	Token      Token              `json:"token"`
	FromAddr   string             `json:"from_addr"`
	ToMultisig string             `json:"to_multisig"`
	Amount     pgtype.Numeric     `json:"amount"`
	Status     SweepStatus        `json:"status"`
	TxHash     *string            `json:"tx_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID          pgtype.UUID        `json:"id"`
	Hash        string             `json:"hash"`
	Chain       Chain              `json:"chain"`
	FromAddr    string             `json:"from_addr"`
	ToAddr      string             `json:"to_addr"`
	Amount      pgtype.Numeric     `json:"amount"`
	Token       Token              `json:"token"`
	Status      TxStatus           `json:"status"`
	BlockNumber *int64             `json:"block_number"`
	ConfirmedAt pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	KycTier   KycTier            `json:"kyc_tier"`
	RiskScore int32              `json:"risk_score"`
	Status    UserStatus         `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserAddress struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Chain          Chain              `json:"chain"`
	Address        string             `json:"address"`
	DerivationPath *string            `json:"derivation_path"`
	Tier           Tier               `json:"tier"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Wallet struct {
	ID             pgtype.UUID        `json:"id"`
	Chain          Chain              `json:"chain"`
	Address        string             `json:"address"`
	Tier           Tier               `json:"tier"`
	Purpose        WalletPurpose      `json:"purpose"`
	MultisigAddr   *string            `json:"multisig_addr"`
	DerivationPath *string            `json:"derivation_path"`
	PolicyConfig   []byte             `json:"policy_config"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Withdrawal struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Chain             Chain              `json:"chain"`
	Token             Token              `json:"token"`
	Amount            pgtype.Numeric     `json:"amount"`
	DestinationAddr   string             `json:"destination_addr"`
	Status            WithdrawalStatus   `json:"status"`
	SourceTier        Tier               `json:"source_tier"`
	MultisigOpID      pgtype.UUID        `json:"multisig_op_id"`
	TimeLockExpiresAt pgtype.Timestamptz `json:"time_lock_expires_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ApproverID        pgtype.UUID        `json:"approver_id"`
}
