// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWhitelistEntries = `-- name: CountWhitelistEntries :one
SELECT COUNT(*)::bigint AS total FROM destination_whitelist WHERE revoked_at IS NULL
`

// Used by destination-whitelist rule: if table is empty, allow all (dev mode).
func (q *Queries) CountWhitelistEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWhitelistEntries)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getSigningKeyByAddress = `-- name: GetSigningKeyByAddress :one

SELECT id, staff_id, chain, address, tier, wallet_type, hw_attested, registered_at, revoked_at
FROM staff_signing_keys
WHERE address = $1
  AND chain = $2::chain
  AND tier = $3::tier
  AND revoked_at IS NULL
LIMIT 1
`

type GetSigningKeyByAddressParams struct {
	Address string `json:"address"`
	Column2 Chain  `json:"column_2"`
	Column3 Tier   `json:"column_3"`
}

// Policy Engine SQL Queries (sqlc source)
// These are read-only queries used by the rule evaluators.
// Used by authorized-signer rule: look up active signing key for a given address+chain+tier.
func (q *Queries) GetSigningKeyByAddress(ctx context.Context, arg GetSigningKeyByAddressParams) (StaffSigningKey, error) {
	row := q.db.QueryRow(ctx, getSigningKeyByAddress, arg.Address, arg.Column2, arg.Column3)
	var i StaffSigningKey
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Chain,
		&i.Address,
		&i.Tier,
		&i.WalletType,
		&i.HwAttested,
		&i.RegisteredAt,
		&i.RevokedAt,
	)
	return i, err
}

const getStaffMember = `-- name: GetStaffMember :one
SELECT id, email, name, role, status, created_at
FROM staff_members
WHERE id = $1
`

type GetStaffMemberRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Role      Role               `json:"role"`
	Status    StaffStatus        `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Used to resolve staff role for daily-limit checks.
func (q *Queries) GetStaffMember(ctx context.Context, id pgtype.UUID) (GetStaffMemberRow, error) {
	row := q.db.QueryRow(ctx, getStaffMember, id)
	var i GetStaffMemberRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getWithdrawal = `-- name: GetWithdrawal :one
SELECT id, user_id, chain, token, amount, destination_addr, status, source_tier,
       multisig_op_id, time_lock_expires_at, created_by, created_at, updated_at
FROM withdrawals
WHERE id = $1
`

type GetWithdrawalRow struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Chain             Chain              `json:"chain"`
	Token             Token              `json:"token"`
	Amount            pgtype.Numeric     `json:"amount"`
	DestinationAddr   string             `json:"destination_addr"`
	Status            WithdrawalStatus   `json:"status"`
	SourceTier        Tier               `json:"source_tier"`
	MultisigOpID      pgtype.UUID        `json:"multisig_op_id"`
	TimeLockExpiresAt pgtype.Timestamptz `json:"time_lock_expires_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// Used by engine to load withdrawal record for time-lock and other checks.
func (q *Queries) GetWithdrawal(ctx context.Context, id pgtype.UUID) (GetWithdrawalRow, error) {
	row := q.db.QueryRow(ctx, getWithdrawal, id)
	var i GetWithdrawalRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Chain,
		&i.Token,
		&i.Amount,
		&i.DestinationAddr,
		&i.Status,
		&i.SourceTier,
		&i.MultisigOpID,
		&i.TimeLockExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isDestinationWhitelisted = `-- name: IsDestinationWhitelisted :one
SELECT EXISTS(
    SELECT 1 FROM destination_whitelist
    WHERE chain = $1::chain
      AND address = $2
      AND revoked_at IS NULL
) AS whitelisted
`

type IsDestinationWhitelistedParams struct {
	Column1 Chain  `json:"column_1"`
	Address string `json:"address"`
}

// Used by destination-whitelist rule: check if an address is in the allowlist.
func (q *Queries) IsDestinationWhitelisted(ctx context.Context, arg IsDestinationWhitelistedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isDestinationWhitelisted, arg.Column1, arg.Address)
	var whitelisted bool
	err := row.Scan(&whitelisted)
	return whitelisted, err
}

const sumWithdrawalsToday = `-- name: SumWithdrawalsToday :one
SELECT COALESCE(SUM(amount), 0)::numeric AS total
FROM withdrawals
WHERE created_by = $1
  AND created_at > now() - interval '24 hours'
  AND status != 'cancelled'
`

// Used by daily-limit rule: total withdrawal amount for a staff member in the last 24h.
// Excludes cancelled withdrawals. Returns 0 if none.
func (q *Queries) SumWithdrawalsToday(ctx context.Context, createdBy pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumWithdrawalsToday, createdBy)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}
